# Site settings
title: Federation Playbook
name: Federation Playbook
email: icam@gsa.gov
author:
    name: FICAM
description: Federation Guidance
highlighter: rouge
repo_url: https://github.com/GSA/ficam-federation
baseurl: '/ficam-federation'
branch: federalist-pages

# Federalist overwrites the site.branch value when deploying
# the site.branch was used in dynamic link generation for objects like Edit Page
# we want the dynamic links to send users to the staging branch.  Adding new site variable to ensure federalist doesn't overwrite.
editbranch: staging

# Links
# List links that you would like to appear on the top navigation bar here
navbar:
- title: IDmanagement.gov
  description: Idmanagement.gov
  url: https://www.idmanagement.gov
- title: Federal ICAM Architecture
  description: Federal ICAM Architecture
  url: https://arch.idmanagement.gov
- title: PIV Guides
  description: PIV Guides
  url: https://piv.idmanagement.gov
- title: Federal PKI Guides
  description: Federal PKI Guides
  url: https://fpki.idmanagement.gov


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Introduction
  url: ''
  internal: true
  coll: false
- text: Federation Methodology
  url: federation_methodology
  internal: true
  coll: false
- text: Identify User Population
  url: user_population
  internal: true
  coll: false
- text: Identity Management
  url: identity_management
  internal: true
  coll: false
- text: Credential Service Provider
  url: credential_service_provider
  internal: true
  coll: false
- text: Relying Party
  url: relying_party
  internal: true
  coll: false
- text: Attribute Provider 
  url: attribute_provider
  internal: true
  coll: false
- text: Trust Framework
  url: trust_framework
  internal: true
  coll: false
- text: Federation Architecture
  url: federation_architecture
  internal: true
  coll: false
- text: Federation Implementation
  url: federation_implementation
  internal: true
  coll: false
- text: Use Cases
  url: user_cases
  internal: true
  coll: false
- text: Contribute
  url: contribute
  internal: true
  coll: false
include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
